name: provadelaco
description: A new Flutter project.
publish_to: "none"

version: 1.5.4+37

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  carousel_slider: ^5.0.0
  dio: ^5.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  sign_in_button: ^4.0.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.1
  share_plus: ^12.0.1
  timezone: ^0.11.0
  flutter_timezone: ^5.0.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  brasil_fields: ^1.17.0
  pub_semver: ^2.1.5
  package_info_plus: ^9.0.0
  easy_image_viewer: ^1.5.1
  flutter_launcher_icons: ^0.14.3
  skeletonizer: ^2.1.0+1
  flutter_swipe_action_cell: ^3.1.5
  file_picker: ^10.3.2
  json_annotation: ^4.9.0

  command_it: ^9.5.0
  listen_it: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.7.0
  mockito: ^5.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icone.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/sucesso.json
    - assets/lotties/aovivo.json